### PR TITLE
Pull request for WAZO-3812-call-api-tenant-isolation-2

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/105

## test calls: fix tests by homogenizing tenants

Why:

* Call creation is now tenant-aware

## calls: create call add tenant isolation for context

### CODE REVIEW

**Comment by sduthil** [comment]
Integration test failures are expected: Zuul does not take into account branches from https://github.com/wazo-platform/wazo-test-helpers/pull/105

**Comment by sduthil** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (zuul job fixed)

**Review by fblackburn1 — APPROVED** [review]
LGTM fails seem due to wazo-confd mock set_lines not tenant aware

**Review by fblackburn1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
Hahahaha :sob:  @sduthil I leave up to you

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
