### PR TITLE
Pull request for WAZO-1448-event-routing-headers

### PR DESCRIPTION
**Pull request by sduthil**
bus: remove useless method on_ami_event
bus: subscribe to event names directly instead of routing keys

Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1448

Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1448

### CODE REVIEW

**Comment by fblackburn1** [comment]
@sduthil to be clear I leave up to you to fix it

**Comment by sduthil** [comment]
Yes, just did not have the time for it yet :)

**Comment by sboily** [comment]
What the status of this PR?

**Comment by sduthil** [comment]
Waiting for me (or someone else) to make the modification requested by François. I don't know exactly how small this is though.

**Comment by sboily** [comment]
> Waiting for me (or someone else) to make the modification requested by François. I don't know exactly how small this is though.

Is it on planning?

**Comment by sduthil** [comment]
Since it is only a refactoring, it does not get priority. Yes it is planned for the next iteration: https://wazo-dev.atlassian.net/browse/WAZO-1448.

**Comment by sduthil** [comment]
Do you need this branch?

**Comment by sboily** [comment]
> Do you need this branch?

nope, but i would like to know why it's always here, and is it on planning. This is only to understand :), thank you for your feedback.

**Comment by sduthil** [comment]
recheck

**Comment by fblackburn1** [comment]
The problem is that our tests with a real wazo-amid do not convert events from `xivo` exchange to `wazo-headers` exchange

We should extract our bridge logic from [wazo-webhookd](https://github.com/wazo-platform/wazo-webhookd/blob/master/wazo_webhookd/bin/init_amqp.py) and reuse it in these tests

I pushed two new commits (that will fail) to use exchange headers, but we need to find a solution to bridge `xivo` and `wazo-headers` exchange in this repository

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
Superseded by https://github.com/wazo-platform/wazo-calld/pull/217

**Pull request closed without merging**
