### PR TITLE
Pull request for WAZO-1405-remove-calld-startup-dependency

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/39

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
reheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fblackburn1** [comment]
No need to force recheck, the failing test `test_event_destination_node_created` is a bug on master branch (with asterisk 16.7) and is under investigation

**Comment by sduthil** [comment]
There are also these tests failing:
```
ERROR: test_given_no_ssl_certificate_when_calld_starts_then_calld_stops (suite.test_https.TestHTTPSMissingCertificate)
ERROR: test_given_no_ssl_private_key_when_calld_starts_then_calld_stops (suite.test_https.TestHTTPSMissingPrivateKey)
```

**Comment by fredericlepied** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Pull request merged**
