### PR TITLE
WAZO-3006: `calld` publish to wazo headers

### PR DESCRIPTION
**Pull request by ja0x**

### CODE REVIEW

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
grepping for `routing` leave some of helpers, please remove them if not used

**Comment by fblackburn1** [comment]
`send_event` from `integration_tests/suite/helpers/bus.py` doesn't seems to use `routing_key` neither

**Review by fblackburn1 — APPROVED** [review]

**Comment by ja0x** [comment]
regate

**Comment by ja0x** [comment]
regate

**Pull request merged**
