### PR TITLE
Wp 554 mobile keeps ringing

### PR DESCRIPTION
**Pull request by pc-m**
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/53

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
> Build failed.
> 
> * [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/4e8d7b5ac9d44ca19f5fca4edc6a6e32) : FAILURE in 4m 11s
> * [wazo-tox-py37 ](https://zuul.wazo.community/zuul/t/local/build/3e4832bb3cb94586831fe102fcfddf0f) : SUCCESS in 5m 07s
> * [debian-packaging ](https://zuul.wazo.community/zuul/t/local/build/52275bc57ff14da7b1380dffa9500314) : SUCCESS in 4m 16s
> * [calld-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/42e2bf3372274fddbe0885fb61fac68d) : SUCCESS in 1h 02m 36s

black has been fixed

**Comment by sduthil** [comment]
Rebased + fix `flake8` error.

**Comment by sduthil** [comment]
recheck

**Review by sduthil — APPROVED** [review]

**Review by sduthil — APPROVED** [review]

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
Force-merged because the failures are not linked to the PR.

**Comment by sduthil** [comment]
Force-merged because the failures are not linked to the PR.

**Pull request merged**
