### PR TITLE
calls: use WAZO_ENTRY_EXTEN for dialed_extension

### PR DESCRIPTION
**Pull request by sduthil**
Why:

* Group members of type "extension" will override XIVO_BASE_EXTEN

### CODE REVIEW

**Comment by fblackburn1** [comment]
Should we change these lines too?
https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/services.py#L297
https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/services.py#L316

**Comment by sduthil** [comment]
> Should we change these lines too?
> https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/services.py#L297
> https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/services.py#L316

Yes! I'll take care of it, thanks!

**Comment by sduthil** [comment]
> Should we change these lines too?
> https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/services.py#L297
> https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/services.py#L316
> 
> edit: If so, then we should also add WAZO_ENTRY_EXTEN in https://github.com/wazo-platform/wazo-asterisk-config/blob/master/etc/asterisk/ari.d/01-wazo.conf#L4

Fixed the two lines and created a new PR for wazo-asterisk-config: https://github.com/wazo-platform/wazo-asterisk-config/pull/39

**Review by fblackburn1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
recheck

**Pull request merged**
