### PR TITLE
tests: increase multiple timeouts

### PR DESCRIPTION
**Pull request by pc-m**
the are some fails some of the time when running in the CI

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
> Build failed.
> 
> * [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/930f64c56b064b6f8c67a1a2f93f3296) : SUCCESS in 3m 16s
> * [wazo-tox-py37 ](https://zuul.wazo.community/zuul/t/local/build/6191628342924ac8bc82c35ef43c77a9) : SUCCESS in 3m 04s
> * [debian-packaging ](https://zuul.wazo.community/zuul/t/local/build/1dee8c9f6583464ba39adb89704e4187) : SUCCESS in 4m 09s
> * [calld-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/ceead7975cae4b3381e3b6e4d86af136) : FAILURE in 1h 03m 21s

Failed on dtmf event test. Increasing timeouts there also

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Review by bloom1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
@pc-m in case you forget: tag is missing to be merged

**Comment by bloom1** [comment]
regate

**Pull request merged**
