### PR TITLE
Add lock to avoid multiple answers on held calls on switchboards

### PR DESCRIPTION
**Pull request by xxbillouxx**

### CODE REVIEW

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by fblackburn1** [comment]
@xxbillouxx it's not normal to trigger recheck when a test added in the same PR fail 75% of the time

**Pull request merged**
