### PR TITLE
Add lock to avoid multiple holds on switchboards

### PR DESCRIPTION
**Pull request by xxbillouxx**

### CODE REVIEW

**Comment by bloom1** [comment]
Hello @xxbillouxx,

Is this PR and the other one in Draft mode relevant? If not, could we close them?

Thank you!

**Comment by xxbillouxx** [comment]
waiting https://github.com/wazo-platform/wazo-calld/pull/258 merged

**Comment by xxbillouxx** [comment]
> Hello @xxbillouxx,
> 
> Is this PR and the other one in Draft mode relevant? If not, could we close them?
> 
> Thank you!

Hi, yes I'm waiting another PR being merged before updating this one.

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Review by bloom1 — APPROVED** [review]
Great :smiley:

**Comment by bloom1** [comment]
recheck

**Pull request merged**
