### PR TITLE
WAZO-2509 Bus consumes on headers instead of topics (routing keys)

### PR DESCRIPTION
**Pull request by ja0x**
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/52

### CODE REVIEW

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Review by fblackburn1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
regate

**Comment by ja0x** [comment]
regate

**Pull request merged**
